#
# ci tool setup
#
# https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops
#
trigger:
  branches:
    include:
    - '*'
#
pr:
- '*'
#
variables:
# non-bufered stdout/stderr
  PYTHONUNBUFFERED: 1
#
jobs:
#
- job: basic_build
#
  pool:
    vmImage: ubuntu-18.04
#
  steps:
#
  - bash: env|sort
    displayName: review enviro
#
  - task: UsePythonVersion@0
    displayName: python version
    inputs:
      versionSpec: 3.8
#
  - task: CopyFiles@2
    inputs:
      sourceFolder: tool/azure/home
      targetFolder: $(HOME)
      contents: '**'
      overWrite: true
    displayName: copy config
#
  - script: tool/azure/setup.sh
    displayName: install deps
#
  - template: tool/azure/steps-cache.yml
    parameters: # change to reset cache
      cache_version: V16
#
  - bash: env|sort|grep CACHE
    displayName: review caches
#
  - template: tool/azure/steps-image.yml
    parameters: # conditional cached build
      image_path: arch/base
      has_active: or(eq(variables.HAS_CACHE_ARCHIVE, 'false'),eq(variables.HAS_CACHE_RESOURCE, 'false'))
#
  - template: tool/azure/steps-image.yml
    parameters:
      image_path: test/cryptsetup
#
  - template: tool/azure/steps-image.yml
    parameters:
      image_path: test/dropbear
#
  - template: tool/azure/steps-image.yml
    parameters:
      image_path: test/tinysshd
#
  - template: tool/azure/steps-image.yml
    parameters:
      image_path: test/unitada
#
  - template: tool/azure/steps-image.yml
    parameters:
      image_path: test/nftables
#
  - bash: machinectl --all --full
    displayName: review machines
#